version: "3.9"
   
services:
  db:
    image: postgres:11
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file: .env-db
    ports:
      - 5432:5432
  web:
    build: .
    command: gunicorn config.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code/
    expose:
      - 8000
    env_file: .env
    depends_on:
      - db