version: "3.9"
   
services:
  db:
    image: postgres:11
    restart: always
    volumes:
      - blog_data:/var/lib/postgresql/data/
    env_file: .env-db
    ports:
      - 5432:5432
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - 8000:8000
    env_file: .env
    depends_on:
      - db

volumes:
  blog_data:
    external: true