version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Testing testing
          command: |
            echo "Hello, World!"
workflows:
  run-hello:
    jobs:
      - build